name: Automatically submit several package updates to Windows Package Manager Community Repository

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"
jobs:
  winget:
    name: Publish winget packages
    runs-on: windows-2025
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Update PSResource
        run: Install-PSResource Microsoft.PowerShell.PSResourceGet -TrustRepository
      - name: Install Winget PowerShell
        run:           Install-PSResource Microsoft.WinGet.Client   -TrustRepository
      - name: Update winget
        run: |
          .\Update-Winget.ps1
      - name: Install wingetcreate
        run: Install-WinGetPackage -Id Microsoft.Wingetcreate
      - name: Update NVDA
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT }}
        run: |
          .\NVAccess.NVDA\update.ps1
      - name: Update REAPER
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT }}
        run: |
          .\Cockos.REAPER\update.ps1
      - name: Update 1Password
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT }}
        run: |
          .\AgileBits.1Password\update.ps1
