name: Automatically submit several package updates to Windows Package Manager Community Repository

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

concurrency:
  group: winget-submission
  cancel-in-progress: false

jobs:
  winget:
    name: Publish winget packages
    runs-on: windows-2025
    env:
      GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT }}
    strategy:
      fail-fast: false
      matrix:
        pkg: [NVAccess.NVDA, NVAccess.NVDA.Beta, Cockos.REAPER]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Winget PowerShell
        run: Install-PSResource Microsoft.WinGet.Client -TrustRepository
      - name: Install wingetcreate
        run: Install-WinGetPackage -Id Microsoft.Wingetcreate
      - name: Update ${{ matrix.pkg }}
        run: .\${{ matrix.pkg }}\update.ps1
